########################################################
#  AUTOMATION
########################################################
- id: Notification_Audio-Duyen_arrived_at_work
  alias: duyen_arrived_at_work
  trigger:
    - platform: state
      entity_id: device_tracker.duyen972_duyengalaxys7
      from: 'not_home'
      to: 'SV-E'
  condition:
    - condition: time
      before: '08:30'
      after: '08:15'
  action:
    - delay: '00:00:30'
    - service: tts.google_say
      entity_id: media_player.kitchen_home
      data:
        message: "Duyen has arrived at work."
        cache: false
- id: web_notify_when_garage_status_changed
  alias: Web Notify when garage open or closed.
  hide_entity: false
  trigger:
    platform: state
    entity_id: cover.garage_door
  action:
    service: notify.html5
    data:
      message: "Garage Door is {% if is_state('cover.garage_door', 'open') %}Open{% else %}Closed{% endif %}!"